-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."group_usermapping" add column "ticket_projectid" bigint
--  null;
