-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."notification_master" add column "call_initiaed_by" uuid
--  null;
