-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."profile_details" add column "group_calling_status" boolean
--  null default 'False';
