-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."organisation_master" add column "form_enable" boolean
--  null default 'false';
